
server:
  port: 8081


spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigfileupload?characterEncoding=utf-8&useSSL=false
    username: root
    password: rootroot
# mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
    map-underscore-to-camel-case: true