
server:
  port: 8081

# nacos????
nacos:
  config:
    bootstrap:
      enable: true
    namespace: DEV
    group: DEFAULT_GROUP
    data-id: springboot-websocket-dev.yml
    type: yaml
    server-addr: 127.0.0.1:8848
    auto-refresh: true